# Generated by Django 5.2.3 on 2025-06-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_start_project', 'can start a new project')]},
        ),
    ]
