# Generated by Django 5.2.3 on 2025-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('not_started', 'Not_started'), ('in_progress', 'In_progress'), ('in_review', 'In_review'), ('in_test', 'In_Test'), ('completed', 'Completed')], default='Not_started', max_length=20)),
                ('dead_line', models.DateField()),
                ('Priority', models.CharField()),
            ],
        ),
    ]
